# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    env_file:
      - .env
    ports:
      - '27017:27017'
    volumes:
      # - ./script-init.js:/docker-entrypoint-initdb.d/script-init.js
      - ./data/mongo:/data/db
      - ./data/backup:/backup
      - ./data/mongo/log:/var/log/mongodb/

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    container_name: mongoExpress
    ports:
      - 8081:8081
    env_file:
      - .env
    links:
      - mongo
    depends_on:
      - mongo

  api-catoexpress:
    restart: unless-stopped
    container_name: api-catoexpress
    build:
      context: ./
      dockerfile: Dockerfile
    image: haroldosorioflores/catoexpress:api-prod.1.0
    volumes:
      - ./dist:/app/dist/
    env_file:
      - .env
    ports:
      - '4000:4000'
    depends_on:
      - mongo
